Tasks/part1/lesson03
Lexsus96/JavaEDC pull request #3
Opened 2020-07-30 09:21 UTC by Lexsus96

#2

2020-08-03 16:32 UTC, efremov-itcenter requested changes

2020-08-03 16:32 UTC, efremov-itcenter commented on src/main/java/part1/lesson03/Pet.java
> +    public Pet(int uid, String name, Person person, int weight) {
UUID

2020-08-03 16:32 UTC, efremov-itcenter commented on src/main/java/part1/lesson03/Pet.java
> +        return uid == pet.uid &&
Leave `uid` only

2020-08-03 16:32 UTC, efremov-itcenter commented on src/main/java/part1/lesson03/Pet.java
> +    public void setWeight(int weight) {
`double`

2020-08-03 16:32 UTC, efremov-itcenter commented on src/main/java/part1/lesson03/DuplicatePetException.java
> +public class DuplicatePetException extends Exception {
`RuntimeException`

2020-08-03 16:32 UTC, efremov-itcenter commented on src/main/java/part1/lesson03/CardFilePet.java
> +    Map<Integer, Pet> map = new HashMap<>();
`private`

2020-08-03 16:32 UTC, efremov-itcenter commented on src/main/java/part1/lesson03/CardFilePet.java
> +
`Map<String, List<Pet>> map`

2020-08-03 16:32 UTC, efremov-itcenter commented on src/main/java/part1/lesson03/CardFilePet.java
> +    public List<Pet> sortPetsByPerson() {
`public List<Pet> sort(Comparator<Pet> comparator)`

2020-08-03 16:32 UTC, efremov-itcenter commented on src/main/java/part1/lesson03/Solution.java
> +    static CardFilePet cardFilePet = new CardFilePet(){{
`private static final CardFilePet CARD_FILE_PET`

2020-08-11 17:02 UTC, Mezhik commented on src/main/java/part1/lesson03/CardFilePet.java
> +        pet.setName(name);
При изменении имени данное животное по прежнему останется в мапе nameMap по предыдущему имени, не корректно

2020-08-11 17:03 UTC, Mezhik commented on src/main/java/part1/lesson03/CardFilePet.java
> +        return optionalPet.orElse(null);
Можно сделать в одну цепочку и не сохранять ссылку optionalPet

2020-08-11 17:05 UTC, Mezhik commented on src/main/java/part1/lesson03/CardFilePet.java
> +        List<Pet> list = nameMap.getOrDefault(name, null);
При отсутствии ключа и так вернет null
В принципе, если хочешь через Optional - это можно все объединить в одну цепочку
По принципу
return Optional.ofNullable(nameMap.get(name))
. ... дальнейший маппинги

2020-08-11 17:07 UTC, Mezhik commented on src/main/java/part1/lesson03/CardFilePet.java
> +public class CardFilePet {
В целом - если объявить Pet Comparable и добавить еще коллекцию для хранения можно сделать 
добавление O(1) -> O(log n), но при этом получение 
отсортированного списка  O(n log n) -> O(1)

2020-08-19 12:57 UTC, efremov-itcenter approved these changes

2020-08-19 13:24 UTC, merged